# services.yaml

parameters:
    upload_directory: 'C:/Users/HP/Desktop/facturation'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $uploadDirectory: '/chemin/vers/votre/dossier/upload' # Remplacez par le chemin réel
            $publicPath: '%kernel.project_dir%/public'
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'
            $urlHelper: '@Symfony\Component\HttpFoundation\UrlHelper'
